language: go

go:
    - master

before_install:
    - go get -u github.com/golang/dep/cmd/dep

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
    - dep ensure
    - ./build.sh

notifications:
    email: false
