package rpc

import (
	. "github.com/jasonyangshadow/lpmx/paeudo"
	. "github.com/jasonyangshadow/lpmx/utils"
	"time"
)

const (
	MIN       = 10000
	MAX       = 20000
	UIDLENGTH = 16
)

type Request struct {
	Timeout time.Duration
	Cmd     string
	Args    []string
}

type Response struct {
	UId string //generated by the server side
	Pid int
}

type RPC struct {
	Env map[string]string
	Dir string
}

func (server *RPC) Exec(req Request, res *Response) error {
	cmd, err := ProcessContextEnv(req.Cmd, server.Env, server.Dir, req.Timeout, req.Args[0:]...)
	if err != nil {
		return err.Err
	}
	res.UId = RandomString(UIDLENGTH)
	res.Pid = cmd.Process.Pid
	return nil
}
