package rpc

const (
	MIN       = 10000
	MAX       = 20000
	UIDLENGTH = 16
)

type Request struct {
	Timeout string
	Cmd     string
	Args    []string
	Pid     int
}

type Response struct {
	UId    string //generated by the server side
	Pid    int
	RPCMap map[int]string
}
